# GitHub Actions
name: pytest

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Flit
        run: python3 setup.py install
      - name: Install Dependencies
        run: make test
      - name: Test
        run: make test all
      - name: Upload coverage
        uses: codecov/codecov-action@v1
